### ISSUE TITLE
v0.2.0 todo list

### ISSUE THREAD

**Issue by fate0** [fate0/pychrome#3]
- [x] offer REPL interface like chrome-remote-interface (maybe require IPython ?)
- [x] offer stable API
- [x] documents and examples are never enough : )
- [x] add pychrome to [awesome-chrome-devtools](https://github.com/ChromeDevTools/awesome-chrome-devtools) list
- [x] switch to gevent base
